version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: equitylink_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: equitylink
      MYSQL_USER: equitylink_user
      MYSQL_PASSWORD: equitylink_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
